/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bundaran.kasir.view;

//import tokobangunan.kasir.backgroundtask.;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import bundaran.kasir.util.MoveFrameListener;

/**
 *
 * @author dan
 */
public class Cari extends javax.swing.JDialog {

    /**
     * Creates new form TsProgress
     * @param parent
     */
    Kasir kasir;
    ArrayList<ArrayList<String>> dBarangOri;
    
    public Cari(Kasir kasir) {
        
        super((Frame) null, true);
        this.kasir = kasir;
        initComponents();
        setLocationRelativeTo(null);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        progressText = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        idTransaksi = new javax.swing.JTextField();
        labelBarcodeName3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        MoveFrameListener frameListener = new MoveFrameListener(jPanel2);
        addMouseListener(frameListener);
        addMouseMotionListener(frameListener);
        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        progressText.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        progressText.setForeground(new java.awt.Color(255, 255, 255));
        progressText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/kasir/res/logo14.PNG"))); // NOI18N
        progressText.setText("   Cari Transaksi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(progressText, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel13.setText("Toko Duta Bangunan, Kendari, Sulawesi Tenggara");

        idTransaksi.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        idTransaksi.setMargin(new java.awt.Insets(2, 10, 2, 10));
        idTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTransaksiActionPerformed(evt);
            }
        });
        idTransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTransaksiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTransaksiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTransaksiKeyTyped(evt);
            }
        });

        labelBarcodeName3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName3.setText("Masukan ID Transaksi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(labelBarcodeName3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(idTransaksi))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBarcodeName3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ArrayList<ArrayList<String>> getDatabarang(String id){
        dBarangOri = new ArrayList<>();
        ArrayList<ArrayList<String>> r = new ArrayList<>();
        
        for (ArrayList<String> t: kasir.dataPenjualanBarang) {
            ArrayList<String> temp = new ArrayList<>();
            if (t.get(1).toLowerCase().equals(id.toLowerCase())) {
                dBarangOri.add(t);
                System.out.println(t);
                System.out.println("_______");
                temp.add(t.get(0));
                int harga = 0;
                for (ArrayList<String> t2 : kasir.dataBarang) {
                    System.out.println(t2);
                System.out.println("++++++");
                    if (t.get(0).equals(t2.get(0))) {
                        harga = Integer.parseInt(t2.get(3));
                        temp.add(t2.get(1));
                        temp.add(t2.get(3));
                        break;
                    }
                }
                temp.add(t.get(3));
//                temp.add(t.get(4));
                
//                int total = Integer.parseInt(t.get(4)) * harga;
int total = 0;
                temp.add(String.valueOf(total));
                temp.add(t.get(2));
                
                r.add(temp);
            }
        }
        
        return r;
    }
    
    
    private void findTransaction(String id){
        if (kasir.dataPenjualan == null) {
            return;
        }
        
        for (ArrayList<String> dt: kasir.dataPenjualan) {
            if (dt.get(0).toLowerCase().equals(id.toLowerCase())) {
                dispose();
                ArrayList<ArrayList<String>> d = getDatabarang(id);
                new HasilCari(true,kasir, dt, d, dBarangOri).setVisible(true);
                return;
            }
        }
        
        
        JOptionPane.showMessageDialog(null, "Data transaksi tidak ditemukan");
    }
    
    private void idTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTransaksiActionPerformed
        findTransaction(idTransaksi.getText());
    }//GEN-LAST:event_idTransaksiActionPerformed

    private void idTransaksiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTransaksiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        }
    }//GEN-LAST:event_idTransaksiKeyPressed

    private void idTransaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTransaksiKeyReleased

    }//GEN-LAST:event_idTransaksiKeyReleased

    private void idTransaksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTransaksiKeyTyped

    }//GEN-LAST:event_idTransaksiKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idTransaksi;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelBarcodeName3;
    private javax.swing.JLabel progressText;
    // End of variables declaration//GEN-END:variables
}
