/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bundaran.kasir.view;

//import tokobangunan.kasir.backgroundtask.;
import annas.jdbc.service.configuration.MyTableModel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import bundaran.kasir.util.MoveFrameListener;
import bundaran.kasir.util.NumberValidation;

/**
 *
 * @author dan
 */
public final class HasilCari extends javax.swing.JDialog {

    ArrayList<String> dataPembeli;
    ArrayList<ArrayList<String>> dataBarang;
    ArrayList<ArrayList<String>> dataBarangOriginal;
    String totalHarga;
    Kasir kasir;
    boolean fromSearching;
    //ArrayList<ArrayList<String>> barangBelanjaan;

    public HasilCari(boolean fromSearching, Kasir kasir, ArrayList<String> dataPembeli, ArrayList<ArrayList<String>> dataBarang,
            ArrayList<ArrayList<String>> dataBarangOriginal) {

        super((Frame) null, true);
        this.kasir = kasir;
        this.dataBarangOriginal = dataBarangOriginal;
        this.dataPembeli = dataPembeli;
        this.fromSearching = fromSearching;
        this.dataBarang = dataBarang;

        if (!fromSearching) {
            this.dataBarangOriginal = dataBarang;
            this.dataBarang = getDatabarang(dataPembeli.get(0));
        }

        initComponents();
        setLocationRelativeTo(null);
//        KeyEvent event = new KeyEvent(this, WIDTH, WIDTH, WIDTH, WIDTH);
//        event.setKeyCode(KeyEvent.VK_ENTER);
//        switch (event.getKeyCode()) {
//        case KeyEvent.VK_ENTER:this.dispose();
//            break;
//        case KeyEvent.VK_ESCAPE:this.dispose();
//            break;
//        default:
//            break;
//        }
        setToTable();
        setdata();
    }

    private ArrayList<ArrayList<String>> getDatabarang(String id) {
        //dBarangOri = new ArrayList<>();
        ArrayList<ArrayList<String>> r = new ArrayList<>();

        for (ArrayList<String> t : dataBarang) {
            ArrayList<String> temp = new ArrayList<>();
            //if (t.get(1).toLowerCase().equals(id.toLowerCase())) {
            //dBarangOri.add(t);
            temp.add(t.get(0));
            int harga = 0;
            for (ArrayList<String> t2 : kasir.dataBarang) {
                if (t.get(0).equals(t2.get(0))) {
                    harga = Integer.parseInt(t2.get(3));
                    temp.add(t2.get(1));
                    break;
                }
            }
            temp.add(t.get(3));
            temp.add(t.get(4));

            int total = Integer.parseInt(t.get(4)) * harga;
            temp.add(String.valueOf(total));

            r.add(temp);
            //}
        }

        return r;
    }

    void setToTable() {
        String[] colNames = new String[]{"Nomor Barcode", "Nama Barang", "Harga", "Jumlah", "diskon" ,"Total Harga (Rp)"};
        MyTableModel model = new MyTableModel(colNames, dataBarang, false, true, new int[]{0}, ",");
        tabelBarang.setModel(model);
        tabelBarang.setRowSelectionAllowed(false);
//        System.out.println(dataBarang);


    }

    synchronized void setdata() {
        NumberValidation nv = new NumberValidation(",", "Rp ");

//        int mustPay = Integer.parseInt(dataPembeli.get(1)) - Integer.parseInt(dataPembeli.get(1));
        int mustPay = 0;
//        System.out.println(dataPembeli);
        labelBarcodeName11.setText("DATA TRANSAKSI : " + dataPembeli.get(0));
        labelId.setText(":  " + nv.fieldChecked(dataPembeli.get(3)));


        sincronDiscount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        progressText = new javax.swing.JLabel();
        progressText7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        labelBarcodeName10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        labelBarcodeName3 = new javax.swing.JLabel();
        labelBarcodeName11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        MoveFrameListener frameListener = new MoveFrameListener(jPanel2);
        addMouseListener(frameListener);
        addMouseMotionListener(frameListener);
        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        progressText.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        progressText.setForeground(new java.awt.Color(255, 255, 255));
        progressText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/kasir/res/logo14.PNG"))); // NOI18N
        progressText.setText("   Data");

        progressText7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        progressText7.setForeground(new java.awt.Color(255, 255, 255));
        progressText7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/kasir/res/close.png"))); // NOI18N
        progressText7.setToolTipText("Tutup");
        progressText7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progressText7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(progressText, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressText7)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progressText7)
                    .addComponent(progressText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel13.setText("Toko Bundaran Elektronik, Kendari, Sulawesi Tenggara");

        tabelBarang.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBarang.setRowHeight(32);
        jScrollPane1.setViewportView(tabelBarang);
        tabelBarang.setDefaultRenderer(Object.class, new TableCellRenderer() {
            private DefaultTableCellRenderer DEFAULT_RENDERER = new DefaultTableCellRenderer();

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = DEFAULT_RENDERER.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (isSelected) {
                    c.setBackground(new Color(0xff8a00));
                } else {
                    c.setBackground(new Color(0xffffff));
                }

                return c;
            }

        });

        labelBarcodeName10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName10.setText("DATA BARANG");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelId.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelId.setForeground(new java.awt.Color(0, 102, 51));
        labelId.setText("ID Transaksi");

        labelBarcodeName3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName3.setText("Total Harga Transaksi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBarcodeName3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBarcodeName3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelBarcodeName11.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        labelBarcodeName11.setForeground(new java.awt.Color(204, 0, 0));
        labelBarcodeName11.setText("DATA TRANSAKSI : DB160720124029");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelBarcodeName10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelBarcodeName11)))
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelBarcodeName11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelBarcodeName10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void progressText7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressText7MouseClicked
        dispose();
        
    }//GEN-LAST:event_progressText7MouseClicked

    void confirmPayment() {
        //if (pay < cost) {
        //  return;
        //}
        FinalCost finalCost = new FinalCost(fromSearching, false, kasir, null, this,
                dataPembeli, dataBarangOriginal
        );

        finalCost.setVisible(true);
        //dispose();
    }

    void sincronDiscount() {

        NumberValidation nv = new NumberValidation(",", "Rp ");

        //Str
//        double getDisount = (discount.getText().isEmpty()) ? 0 : Double.parseDouble(discount.getText());
        double getDisount = 0;
//        double cost = Double.parseDouble(dataPembeli.get(1));
        double cost = 0;
        getDisount = (getDisount * cost) / 100;
        cost = cost - getDisount;

        labelId.setText(":  " + nv.fieldChecked(String.valueOf(cost)));

        int sisaBayar = 0;
//        int sisaBayar = Integer.parseInt(labelId.getText().replace(":  ", "").replace("Rp ", "").replace(",", "")) - Integer.parseInt(dataPembeli.get(1));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBarcodeName10;
    private javax.swing.JLabel labelBarcodeName11;
    private javax.swing.JLabel labelBarcodeName3;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel progressText;
    private javax.swing.JLabel progressText7;
    public javax.swing.JTable tabelBarang;
    // End of variables declaration//GEN-END:variables
}
