/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bundaran.kasir.view;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;
import bundaran.kasir.util.CustomComboBox;
import bundaran.kasir.util.MoveFrameListener;
import bundaran.kasir.util.NumberValidation;
import bundaran.kasir.util.staticIdentifier;

/**
 *
 * @author HAMSTER-BIRU
 */
public final class PayDetails extends javax.swing.JDialog {

    public static PayDetails now;
    ArrayList<ArrayList<String>> dataBarang;
    String totalHarga;
    String IDtransaksi;
    Kasir kasir;

    public PayDetails(Kasir instance, ArrayList<ArrayList<String>> dataBarang, String totalHarga, String IDTransaksi) {
        super((Frame) null, true);
        this.kasir = instance;
        this.IDtransaksi = IDTransaksi;
        this.dataBarang = dataBarang;
        this.totalHarga = totalHarga;

        initComponents();
        bayar.setText("Rp ");
//        discount.setText("Rp ");

        bayar.requestFocus();
        setLocationRelativeTo(null);
        setDetailPay(totalHarga);

        /**
         * Sesuaikan total harga denan diskon yang diberikan
         */
        sincronDiscount();
    }

    void setDetailPay(String totalHarga) {

        costTotal.setText(totalHarga);

//        if (status.getSelectedIndex() == 0) {
//            bayar.requestFocus();
//            buyerName.setEnabled(false);
//            noHp.setEnabled(false);
//            alamat.setEnabled(false);
//            bayar.setEnabled(true);
//            discount.setEnabled(true);
//
//        } else {
//            buyerName.requestFocus();
//            buyerName.setEnabled(true);
//            noHp.setEnabled(true);
//            alamat.setEnabled(true);
//            bayar.setEnabled(false);
//            discount.setEnabled(false);
//        }

    }

    /**
     * Mendapatkan tanggal hari ini yang digunakan untuk tanggal transaksi
     *
     * @return
     */
    private String getTransactionDate() {
        Date date = new Date();
        String id = String.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(date));
        return id;
    }

    /**
     * Mendapatkan tanggal jatuh tempo jika pembeli belm membayar
     *
     * @return
     */
    private String getDeadlineDate() {
        Date date = new Date();
        String id = String.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(date));

        int bulan = Integer.parseInt(id.substring(5, 7));
        int tahun = Integer.parseInt(id.substring(0, 4));
        String day = id.substring(8, 10);
        if (bulan == 12) {
            id = id.replace(String.valueOf(tahun), String.valueOf(tahun + 1));
        } else {
            bulan++;
            id = String.valueOf(tahun) + "-" + ((bulan < 10) ? ("0" + String.valueOf(bulan)) : String.valueOf(bulan)) + "-" + day;
        }

        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        progressText1 = new javax.swing.JLabel();
        progressText7 = new javax.swing.JLabel();
        panelDetail = new javax.swing.JPanel();
        labelBarcodeName = new javax.swing.JLabel();
        xxx = new javax.swing.JLabel();
        barcode2 = new javax.swing.JLabel();
        barcode4 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        costTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        barcode7 = new javax.swing.JLabel();
        labelBarcodeName5 = new javax.swing.JLabel();
        labelCashBack = new javax.swing.JLabel();
        labelBarcodeName4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N

        MoveFrameListener frameListenerx = new MoveFrameListener(jPanel2);
        addMouseListener(frameListenerx);
        addMouseMotionListener(frameListenerx);
        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        progressText1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        progressText1.setForeground(new java.awt.Color(255, 255, 255));
        progressText1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/kasir/res/logo14.PNG"))); // NOI18N
        progressText1.setText("   Pembayaran");

        progressText7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        progressText7.setForeground(new java.awt.Color(255, 255, 255));
        progressText7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/kasir/res/close.png"))); // NOI18N
        progressText7.setToolTipText("Tutup");
        progressText7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progressText7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(progressText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressText7)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressText7)
                    .addComponent(progressText1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDetail.setBackground(new java.awt.Color(246, 246, 246));
        panelDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labelBarcodeName.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName.setText("Total Harga");

        xxx.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        xxx.setText("Bayar");

        barcode2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        barcode2.setText(":");

        barcode4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        barcode4.setText(":");

        bayar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        bayar.setMargin(new java.awt.Insets(2, 10, 2, 10));
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bayarKeyTyped(evt);
            }
        });

        costTotal.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        costTotal.setText("Total Harga");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        barcode7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        barcode7.setForeground(new java.awt.Color(204, 0, 51));
        barcode7.setText(":");

        labelBarcodeName5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName5.setForeground(new java.awt.Color(204, 0, 51));
        labelBarcodeName5.setText("Kembalian");

        labelCashBack.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelCashBack.setForeground(new java.awt.Color(204, 0, 51));
        labelCashBack.setText("Rp 0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelBarcodeName5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(barcode7, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCashBack, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(barcode7)
                        .addComponent(labelCashBack))
                    .addComponent(labelBarcodeName5))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDetailLayout = new javax.swing.GroupLayout(panelDetail);
        panelDetail.setLayout(panelDetailLayout);
        panelDetailLayout.setHorizontalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBarcodeName)
                    .addComponent(xxx))
                .addGap(94, 94, 94)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDetailLayout.createSequentialGroup()
                        .addComponent(barcode2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                    .addGroup(panelDetailLayout.createSequentialGroup()
                        .addComponent(barcode4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bayar)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDetailLayout.setVerticalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(barcode2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(costTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelBarcodeName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xxx, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(barcode4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelBarcodeName4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName4.setText("RINCIAN TOTAL BELANJA");

        jLabel13.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel13.setText("Toko Bundaran Elektronik, Kendari, Sulawesi Tenggara");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelBarcodeName4)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(panelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelBarcodeName4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void progressText7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressText7MouseClicked

        dispose();
    }//GEN-LAST:event_progressText7MouseClicked

    private void bayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        }
    }//GEN-LAST:event_bayarKeyTyped

    private void bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyReleased
        /*        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        } else {*/
            NumberValidation nv = new NumberValidation(",", "Rp ");
            bayar.setText(nv.fieldChecked(bayar.getText()));

            getCashBack();
            //}
    }//GEN-LAST:event_bayarKeyReleased

    private void bayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        } else {
            NumberValidation nv = new NumberValidation(",", "Rp ");
            bayar.setText(nv.fieldChecked(bayar.getText()));

            getCashBack();
        }
    }//GEN-LAST:event_bayarKeyPressed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        confirmPayment(null, null);
    }//GEN-LAST:event_bayarActionPerformed

    /**
     * Menghitung nilai kembalian
     */
    private void getCashBack() {
        if (this.bayar.getText().isEmpty()
                || this.bayar.getText().replace("Rp ", "").replace(",", "").isEmpty()) {
            return;
        }

        int total = Integer.parseInt(costTotal.getText().replace("Rp ", "").replace(",", ""));
        int pay = Integer.parseInt(this.bayar.getText().replace("Rp ", "").replace(",", ""));

        if (pay >= total) {
            NumberValidation nv = new NumberValidation(",", "Rp ");
            int back = pay - total;
            labelCashBack.setText(nv.fieldChecked(String.valueOf(back)));
        } else {
            labelCashBack.setText("Rp 0");
        }

    }

    /**
     * Menyesuaikan harga belanjaan total dengan diskon yang didapat
     */
    void sincronDiscount() {
//        if (discount.getText().isEmpty()) {
//            costTotal.setText(totalHarga);
//            return;
//        }
//
//        if (discount.getText().equals("Rp ")) {
//            costTotal.setText(totalHarga);
//            return;
//        }
//
//        int getDisount = Integer.parseInt(discount.getText().replace("Rp ", "").replace(",", ""));
        int cost = Integer.parseInt(totalHarga.replace("Rp ", "").replace(",", ""));
//        getDisount = (getDisount * cost) / 100;
//        cost = cost - getDisount;

        NumberValidation nv = new NumberValidation(",", "Rp ");
        costTotal.setText(nv.fieldChecked(String.valueOf(cost)));
    }


    /**
     * Data dari pembeli baik yang lunas maupun tidak lunas
     *
     * @return
     */
    private ArrayList<String> dataPembeli() {
        ArrayList<String> data = new ArrayList<>();
        data.add(IDtransaksi);
        data.add(getTransactionDate());
//        data.add((buyerName.getText().isEmpty()) ? "" : buyerName.getText());
//        data.add((noHp.getText().isEmpty()) ? "" : noHp.getText());
//        data.add((status.getSelectedIndex() == 0) ? "LUNAS" : "BELUM LUNAS");
//        data.add((status.getSelectedIndex() == 0) ? "" : getDeadlineDate());
//        data.add((status.getSelectedIndex() == 0) ? getTransactionDate() : "");
//        data.add(discount.getText().replace("Rp ", "").replace(",", ""));
        data.add("0");
        data.add(totalHarga.replace("Rp ", "").replace(",", ""));
//        data.add(alamat.getText());
        data.add(Login.USER_LOGGED);
        return data;
    }

    /**
     * Data barang yang akan disimpan untuk tiap poses transsaksi
     *
     * @return
     */
    private ArrayList<ArrayList<String>> dataBarang() {
        ArrayList<ArrayList<String>> data = new ArrayList<>();

        for (ArrayList<String> brg : dataBarang) {
            ArrayList<String> temp = new ArrayList<>();

            temp.add(brg.get(0)/*untuk nomor barcode*/);
            temp.add(IDtransaksi);
//            temp.add((status.getSelectedIndex() == 0) ? "LUNAS" : "BELUM LUNAS");
            temp.add(brg.get(5));
            temp.add(brg.get(2));
            temp.add(brg.get(4).replace("Rp ", "").replace(",", ""));

            data.add(temp);
        }

        return data;
    }

    /**
     * Fngsi yang digunakan untuk mengkonfirmasi pembayaran dan akandisimpan ke
     * database
     *
     * @param buyerdata
     * @param productChart
     */
    private void confirmPayment(ArrayList<String> buyerdata /* data untk tabel data_penjualan*/,
            ArrayList<ArrayList<String>> productChart /* data untuk tabel data_penjualan_barang*/) {

//        if (discount.getText().isEmpty()) {
//            discount.setText("Rp ");
//        }

        buyerdata = dataPembeli();
        productChart = dataBarang();

//        if (status.getSelectedIndex() == 0) { // jika pembayarannya lagsung lunas

            if (bayar.getText().isEmpty()) {
                return;
            }

            int totalV = Integer.parseInt(costTotal.getText().replace(",", "").replace("Rp ", ""));
            int bayarV = (!bayar.getText().replace("Rp ", "").isEmpty())
                    ? Integer.parseInt(this.bayar.getText().replace(",", "").replace("Rp ", "")) : 0;

            if (bayarV >= totalV) {
                
                    new FinalCost(false,
                            true,
                            kasir, this, null, buyerdata, productChart,
                            String.valueOf(totalV),
                            String.valueOf(bayarV))
                            .setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "Periksa kolom uang bayar...");
            }

//        } else {
//            if (buyerName.getText().isEmpty() || noHp.getText().isEmpty() || alamat.getText().isEmpty()) {
//                return;
//            }
//
//            if (bayarSebagian.isSelected()) {
//                now = this;
//                HasilCari hasilCari = new HasilCari(false,kasir, buyerdata, productChart, kasir.dataBarang);
//                hasilCari.setVisible(true);
//
//            } else {
//
//                setVisible(false);
//                PayUnLunas unLunas = new PayUnLunas(kasir, this, buyerdata, productChart);
//                unLunas.setVisible(true);
//            }
//        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(new WindowsLookAndFeel());
            new PayDetails(null, null, null, null).setVisible(true);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(PayDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barcode2;
    private javax.swing.JLabel barcode4;
    private javax.swing.JLabel barcode7;
    private javax.swing.JTextField bayar;
    private javax.swing.JLabel costTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBarcodeName;
    private javax.swing.JLabel labelBarcodeName4;
    private javax.swing.JLabel labelBarcodeName5;
    private javax.swing.JLabel labelCashBack;
    private javax.swing.JPanel panelDetail;
    private javax.swing.JLabel progressText1;
    private javax.swing.JLabel progressText7;
    private javax.swing.JLabel xxx;
    // End of variables declaration//GEN-END:variables
}
