/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bundaran.kasir.view;

//import tokobangunan.kasir.backgroundtask.;
import annas.jdbc.service.configuration.MyTableModel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import bundaran.kasir.util.MoveFrameListener;
import bundaran.kasir.util.NumberValidation;

/**
 *
 * @author dan
 */
public final class PayHalf extends javax.swing.JDialog {

    ArrayList<String> dataPembeli;
    ArrayList<ArrayList<String>> dataBarang;
    ArrayList<ArrayList<String>> dataBarangOriginal;
    String totalHarga;
    Kasir kasir;
    //boolean fromSearching;

    public PayHalf(Kasir kasir, ArrayList<String> dataPembeli, ArrayList<ArrayList<String>> dataBarang,
            ArrayList<ArrayList<String>> dataBarangOriginal) {

        super((Frame) null, true);
        this.kasir = kasir;
        this.dataBarangOriginal = dataBarangOriginal;
        this.dataPembeli = dataPembeli;
        //this.fromSearching = fromSearching;
        this.dataBarang = dataBarang;

        //if (!fromSearching) {
        this.dataBarang = getDatabarang(dataPembeli.get(0));
        ///}

        initComponents();
        setLocationRelativeTo(null);

        setToTable();
        setdata();
        bayar.requestFocus();
    }

    private ArrayList<ArrayList<String>> getDatabarang(String id) {
        //dBarangOri = new ArrayList<>();
        ArrayList<ArrayList<String>> r = new ArrayList<>();

        for (ArrayList<String> t : dataBarang) {
            ArrayList<String> temp = new ArrayList<>();
            //if (t.get(1).toLowerCase().equals(id.toLowerCase())) {
            //dBarangOri.add(t);
            temp.add(t.get(0));
            int harga = 0;
            for (ArrayList<String> t2 : kasir.dataBarang) {
                if (t.get(0).equals(t2.get(0))) {
                    harga = Integer.parseInt(t2.get(3));
                    temp.add(t2.get(1));
                    break;
                }
            }
            temp.add(t.get(3));
            temp.add(t.get(4));

            int total = Integer.parseInt(t.get(4)) * harga;
            temp.add(String.valueOf(total));

            r.add(temp);
            //}
        }

        return r;
    }

    void setToTable() {
        String[] colNames = new String[]{"Nomor Barcode", "Nama Barang", "Jenis Pembelian", "Jumlah", "Total Harga (Rp)"};
        MyTableModel model = new MyTableModel(colNames, dataBarang, false, true, new int[]{0}, ",");
        tabelBarang.setModel(model);
        tabelBarang.setRowSelectionAllowed(false);

    }

    synchronized void setdata() {
        NumberValidation nv = new NumberValidation(",", "Rp ");

        int mustPay = Integer.parseInt(dataPembeli.get(8)) - Integer.parseInt(dataPembeli.get(10));
        terbayar.setText("Total Transaksi yang telah terbayar : " + nv.fieldChecked(dataPembeli.get(10)));
        labelBarcodeName11.setText("DATA TRANSAKSI : " + dataPembeli.get(0));
        labelId.setText(":  " + nv.fieldChecked(dataPembeli.get(8)));
        labelNamaPembeli.setText(":  " + dataPembeli.get(2));
        labelKkontak.setText(":  " + dataPembeli.get(3));
        labelAlamat.setText(":  " + dataPembeli.get(9));
        labelTglTransaksi.setText(":  " + dataPembeli.get(1));
        labelJatuhTempo.setText(":  " + dataPembeli.get(5));
        discount.setText(dataPembeli.get(7));

        costTotal.setText(nv.fieldChecked(String.valueOf(mustPay)));

        totalHarga = costTotal.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        progressText = new javax.swing.JLabel();
        progressText7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        labelBarcodeName10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelNamaPembeli = new javax.swing.JLabel();
        labelKkontak = new javax.swing.JLabel();
        labelBarcodeName4 = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelBarcodeName5 = new javax.swing.JLabel();
        labelTglTransaksi = new javax.swing.JLabel();
        labelBarcodeName6 = new javax.swing.JLabel();
        labelJatuhTempo = new javax.swing.JLabel();
        labelBarcodeName7 = new javax.swing.JLabel();
        labelBarcodeName8 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        labelBarcodeName3 = new javax.swing.JLabel();
        labelBarcodeName11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bayar = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        labelBarcodeName9 = new javax.swing.JLabel();
        labelBarcodeName14 = new javax.swing.JLabel();
        labelBarcodeName12 = new javax.swing.JLabel();
        costTotal = new javax.swing.JLabel();
        labelBarcodeName13 = new javax.swing.JLabel();
        terbayar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        MoveFrameListener frameListener = new MoveFrameListener(jPanel2);
        addMouseListener(frameListener);
        addMouseMotionListener(frameListener);
        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        progressText.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        progressText.setForeground(new java.awt.Color(255, 255, 255));
        progressText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/kasir/res/logo14.PNG"))); // NOI18N
        progressText.setText("   Data");

        progressText7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        progressText7.setForeground(new java.awt.Color(255, 255, 255));
        progressText7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/kasir/res/close.png"))); // NOI18N
        progressText7.setToolTipText("Tutup");
        progressText7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progressText7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(progressText, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressText7)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progressText7)
                    .addComponent(progressText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel13.setText("Toko Bundaran Elektronik, Kendari, Sulawesi Tenggara");

        discount.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        discount.setMargin(new java.awt.Insets(2, 10, 2, 10));
        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });
        discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                discountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discountKeyTyped(evt);
            }
        });

        tabelBarang.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBarang.setRowHeight(32);
        jScrollPane1.setViewportView(tabelBarang);
        tabelBarang.setDefaultRenderer(Object.class, new TableCellRenderer() {
            private DefaultTableCellRenderer DEFAULT_RENDERER = new DefaultTableCellRenderer();

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = DEFAULT_RENDERER.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (isSelected) {
                    c.setBackground(new Color(0xff8a00));
                } else {
                    c.setBackground(new Color(0xffffff));
                }

                return c;
            }

        });

        labelBarcodeName10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName10.setText("DATA BARANG");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelNamaPembeli.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelNamaPembeli.setForeground(new java.awt.Color(0, 102, 51));
        labelNamaPembeli.setText("ID Transaksi");

        labelKkontak.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelKkontak.setForeground(new java.awt.Color(0, 102, 51));
        labelKkontak.setText("ID Transaksi");

        labelBarcodeName4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName4.setText("Nama Pembeli");

        labelAlamat.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelAlamat.setForeground(new java.awt.Color(0, 102, 51));
        labelAlamat.setText("ID Transaksi");

        labelBarcodeName5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName5.setText("Kontak");

        labelTglTransaksi.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelTglTransaksi.setForeground(new java.awt.Color(0, 102, 51));
        labelTglTransaksi.setText("ID Transaksi");

        labelBarcodeName6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName6.setText("Alamat");

        labelJatuhTempo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelJatuhTempo.setForeground(new java.awt.Color(0, 102, 51));
        labelJatuhTempo.setText("ID Transaksi");

        labelBarcodeName7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName7.setText("Tangal Transaksi");

        labelBarcodeName8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName8.setText("Jatuh Tempo");

        labelId.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelId.setForeground(new java.awt.Color(0, 102, 51));
        labelId.setText("ID Transaksi");

        labelBarcodeName3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName3.setText("Total Harga Transaksi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBarcodeName4)
                    .addComponent(labelBarcodeName5)
                    .addComponent(labelBarcodeName6)
                    .addComponent(labelBarcodeName7)
                    .addComponent(labelBarcodeName8)
                    .addComponent(labelBarcodeName3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelId, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(labelNamaPembeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelKkontak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTglTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelJatuhTempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBarcodeName3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBarcodeName4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBarcodeName5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKkontak, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBarcodeName6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBarcodeName7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBarcodeName8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJatuhTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelBarcodeName11.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        labelBarcodeName11.setForeground(new java.awt.Color(204, 0, 0));
        labelBarcodeName11.setText("DATA TRANSAKSI : DB160720124029");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        bayar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        bayar.setForeground(new java.awt.Color(0, 153, 51));
        bayar.setMargin(new java.awt.Insets(2, 10, 2, 10));
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayarKeyReleased(evt);
            }
        });

        kembalian.setEditable(false);
        kembalian.setBackground(new java.awt.Color(255, 255, 255));
        kembalian.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        kembalian.setForeground(new java.awt.Color(204, 0, 51));
        kembalian.setText("Rp ");
        kembalian.setMargin(new java.awt.Insets(2, 10, 2, 10));

        labelBarcodeName9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName9.setText("Bayar                 :");

        labelBarcodeName14.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName14.setForeground(new java.awt.Color(204, 0, 51));
        labelBarcodeName14.setText("Kembalian                  :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBarcodeName9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(labelBarcodeName14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kembalian)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBarcodeName9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBarcodeName14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelBarcodeName12.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName12.setForeground(new java.awt.Color(0, 0, 255));
        labelBarcodeName12.setText("Yang Harus dibayar  :");

        costTotal.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        costTotal.setForeground(new java.awt.Color(0, 0, 255));
        costTotal.setText("Rp ");

        labelBarcodeName13.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName13.setText("Diskon               :");

        terbayar.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        terbayar.setText("Total Transaksi yang telah terbayar :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(terbayar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelBarcodeName11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelBarcodeName10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelBarcodeName13, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelBarcodeName12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(costTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelBarcodeName11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBarcodeName10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(terbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBarcodeName12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(costTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelBarcodeName13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getCashBack() {
        if (this.bayar.getText().isEmpty()
                || this.bayar.getText().replace("Rp ", "").replace(",", "").isEmpty()) {
            return;
        }

        int total = Integer.parseInt(costTotal.getText().replace("Rp ", "").replace(",", ""));
        int pay = Integer.parseInt(this.bayar.getText().replace("Rp ", "").replace(",", ""));

        if (pay >= total) {
            NumberValidation nv = new NumberValidation(",", "Rp ");
            int back = pay - total;
            kembalian.setText(nv.fieldChecked(String.valueOf(back)));
        } else {
            kembalian.setText("Rp 0");
        }

    }

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed
        confirmPayment();
    }//GEN-LAST:event_discountActionPerformed

    private void discountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        } else {
            NumberValidation nv = new NumberValidation("", null);
            //discount.setText(nv.fieldChecked(discount.getText()));
            try {
                if (!discount.getText().isEmpty()) {
                    if (Integer.parseInt(nv.fieldChecked(discount.getText())) > 100) {
                        discount.setText("100");
                    }
                }
                //sincronDiscount();
                getCashBack();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Mohon periksa inputan anda");
            }
        }
    }//GEN-LAST:event_discountKeyPressed

    private void discountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountKeyReleased
        // if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        //   dispose();
        //} else {
        
        NumberValidation nv = new NumberValidation("", null);
        //discount.setText(nv.fieldChecked(discount.getText()));
        try {
            if (!discount.getText().isEmpty()) {
                if (Integer.parseInt(nv.fieldChecked(discount.getText())) > 100) {
                    discount.setText("100");
                }
            }
            sincronDiscount();
            getCashBack();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Mohon periksa inputan anda");
        }
        
    }//GEN-LAST:event_discountKeyReleased

    private void discountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountKeyTyped

    }//GEN-LAST:event_discountKeyTyped

    private void bayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        } else {
            NumberValidation nv = new NumberValidation(",", "Rp ");
            bayar.setText(nv.fieldChecked(bayar.getText()));

            getCashBack();
        }
    }//GEN-LAST:event_bayarKeyPressed

    private void bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyReleased
//        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
        //          dispose();
        //    } else {
        NumberValidation nv = new NumberValidation(",", "Rp ");
        bayar.setText(nv.fieldChecked(bayar.getText()));

        getCashBack();
        //  }
    }//GEN-LAST:event_bayarKeyReleased

    private void progressText7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressText7MouseClicked
        dispose();
    }//GEN-LAST:event_progressText7MouseClicked

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed

        confirmPayment();
    }//GEN-LAST:event_bayarActionPerformed

    void confirmPayment() {
        if (bayar.getText().replace("Rp ", "").replace(",", "").isEmpty()) {
            return;
        }

        int pay = Integer.parseInt(bayar.getText().replace("Rp ", "").replace(",", ""));
        int cost = Integer.parseInt(costTotal.getText().replace("Rp ", "").replace(",", ""));

        //if (pay < cost) {
        //  return;
        //}
        //dispose();
    }

    void sincronDiscount() {
        if (discount.getText().isEmpty()) {
            costTotal.setText(totalHarga);
            return;
        }

        if (discount.getText().equals("0")) {
            costTotal.setText(totalHarga);
            return;
        }

        double getDisount = Double.parseDouble(discount.getText());
        double cost = Double.parseDouble(totalHarga.replace("Rp ", "").replace(",", ""));
        getDisount = (getDisount * cost) / 100;
        cost = cost - getDisount;

        NumberValidation nv = new NumberValidation(",", "Rp ");
        costTotal.setText(nv.fieldChecked(String.valueOf(cost)));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JLabel costTotal;
    private javax.swing.JTextField discount;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kembalian;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelBarcodeName10;
    private javax.swing.JLabel labelBarcodeName11;
    private javax.swing.JLabel labelBarcodeName12;
    private javax.swing.JLabel labelBarcodeName13;
    private javax.swing.JLabel labelBarcodeName14;
    private javax.swing.JLabel labelBarcodeName3;
    private javax.swing.JLabel labelBarcodeName4;
    private javax.swing.JLabel labelBarcodeName5;
    private javax.swing.JLabel labelBarcodeName6;
    private javax.swing.JLabel labelBarcodeName7;
    private javax.swing.JLabel labelBarcodeName8;
    private javax.swing.JLabel labelBarcodeName9;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelJatuhTempo;
    private javax.swing.JLabel labelKkontak;
    private javax.swing.JLabel labelNamaPembeli;
    private javax.swing.JLabel labelTglTransaksi;
    private javax.swing.JLabel progressText;
    private javax.swing.JLabel progressText7;
    public javax.swing.JTable tabelBarang;
    private javax.swing.JLabel terbayar;
    // End of variables declaration//GEN-END:variables
}
