/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bundaran.kasir.view;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import bundaran.kasir.util.CustomComboBox;
import bundaran.kasir.util.MoveFrameListener;
import bundaran.kasir.util.NumberValidation;

/**
 *
 * @author HAMSTER-BIRU
 */
public final class ProductDetail extends javax.swing.JDialog {

    ArrayList<ArrayList<String>> dataBarang;
    Kasir instance;
    String[] textIdentifier;
    ArrayList<String> dataSelected = null;
    boolean add;

    public ProductDetail(Kasir instance, boolean add, ArrayList<ArrayList<String>> dataBarang, String... textIdentifier) {
        super(instance, true);
        
        
        this.add = add;
        this.dataBarang = dataBarang;
        this.instance = instance;
        this.textIdentifier = textIdentifier;
        
        initComponents();
        setLocationRelativeTo(null);
        //this.requestFocus();

        if (add) {
            total.setText("1");
            diskon.setText("0");
        } else {
            total.setText(textIdentifier[1]);
            NumberValidation nv = new NumberValidation(",", "Rp ");
            diskon.setText((String.valueOf(textIdentifier[3]).equals("0"))? "Rp " : nv.fieldChecked(String.valueOf(textIdentifier[3])));
            cost.setText(nv.fieldChecked(String.valueOf(textIdentifier[2])));            
        }

        if (dataBarang != null) {
            dataSelected = findProduct(textIdentifier[0]);
            setDetail();
            
        }
        

    }

    DefaultComboBoxModel<String> setBox() {

        if (!dataSelected.get(7).isEmpty()) {
            return new DefaultComboBoxModel<>(new String[]{dataSelected.get(6), "Item"});
        } else {
            return new DefaultComboBoxModel<>(new String[]{dataSelected.get(6)});
        }
    }

    public void sendDetail(KeyEvent evt) {
        Kasir.isDetailShow = false;
        
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                if (total.getText().isEmpty() || total.getText().equals("0")) {
                    break;
                }

                String price = cost.getText().replace("Rp ", "").replace(",", "");
                String diskon = (this.diskon.getText().replace("Rp ", "").replace(",", "").equals("")) ? "0":this.diskon.getText().replace("Rp ", "").replace(",", "");
                instance.catchUpDetail(add, barcode.getText(), barcodeName.getText(),
                        total.getText(), 
                        String.valueOf(Long.parseLong(dataSelected.get(3))), diskon, price);
                dispose();
                break;
            case KeyEvent.VK_ESCAPE:
                JTextField field = (JTextField) instance.jComboBox1.getEditor().getEditorComponent();
                field.setText("");
                instance.setToTable();
                instance.jComboBox1.requestFocus();
                dispose();
                break;
            default:

                break;
        }
    }

    private ArrayList<String> findProduct(String id) {
        boolean find = false;

        int index = 0;
        for (int i = 0; i < dataBarang.size(); i++) {
            if (id.toLowerCase().equals(dataBarang.get(i)
                    /* i adalah urutan untuk nomor barcode barang*/.get(0).toLowerCase())) {
                find = true;
                index = i;
                break;
            }
        }

        if (find) {
            //labelBarcode.setText("ketemu");
            //empty.setVisible(false);
            return dataBarang.get(index);
        }

        //empty.setText("Tidak ada data yang ditemukan");
        panelDetail.setVisible(false);
        return null;
    }

    private void setDetail() {

        barcode.setText(dataSelected.get(0));
        barcodeName.setText(dataSelected.get(1));

        setCostTotal(total.getText().replace(",", ""), diskon.getText().replace(",", ""));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        progressText1 = new javax.swing.JLabel();
        progressText7 = new javax.swing.JLabel();
        panelDetail = new javax.swing.JPanel();
        labelBarcode = new javax.swing.JLabel();
        barcode = new javax.swing.JLabel();
        barcodeName = new javax.swing.JLabel();
        labelBarcodeName = new javax.swing.JLabel();
        labelBarcodeName1 = new javax.swing.JLabel();
        labelBarcodeName2 = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        barcode1 = new javax.swing.JLabel();
        barcode2 = new javax.swing.JLabel();
        barcode3 = new javax.swing.JLabel();
        barcode4 = new javax.swing.JLabel();
        barcode5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        diskon = new javax.swing.JTextField();
        labelBarcodeName4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N

        MoveFrameListener frameListenerx = new MoveFrameListener(jPanel2);
        addMouseListener(frameListenerx);
        addMouseMotionListener(frameListenerx);
        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        progressText1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        progressText1.setForeground(new java.awt.Color(255, 255, 255));
        progressText1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/kasir/res/logo14.PNG"))); // NOI18N
        progressText1.setText("   Rincian Barang");

        progressText7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        progressText7.setForeground(new java.awt.Color(255, 255, 255));
        progressText7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/kasir/res/close.png"))); // NOI18N
        progressText7.setToolTipText("Tutup");
        progressText7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progressText7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(progressText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressText7)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressText7)
                    .addComponent(progressText1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDetail.setBackground(new java.awt.Color(255, 255, 255));
        panelDetail.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelBarcode.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcode.setText("Nomor Barcode");

        barcode.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        barcode.setText("jLabel2");

        barcodeName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        barcodeName.setText("jLabel2");

        labelBarcodeName.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName.setText("Nama Barang");

        labelBarcodeName1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName1.setText("Jumlah");

        labelBarcodeName2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName2.setText("Total Harga");

        cost.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cost.setText("jLabel2");

        barcode1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        barcode1.setText(":");

        barcode2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        barcode2.setText(":");

        barcode3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        barcode3.setText(":");

        barcode4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        barcode4.setText(":");

        barcode5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        barcode5.setText(":");

        total.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        total.setMargin(new java.awt.Insets(2, 10, 2, 10));
        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalKeyReleased(evt);
            }
        });

        diskon.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        diskon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                diskonKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                diskonKeyReleased(evt);
            }
        });

        labelBarcodeName4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        labelBarcodeName4.setText("Diskon");

        javax.swing.GroupLayout panelDetailLayout = new javax.swing.GroupLayout(panelDetail);
        panelDetail.setLayout(panelDetailLayout);
        panelDetailLayout.setHorizontalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBarcode)
                    .addComponent(labelBarcodeName)
                    .addComponent(labelBarcodeName1)
                    .addComponent(labelBarcodeName2)
                    .addComponent(labelBarcodeName4))
                .addGap(55, 55, 55)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailLayout.createSequentialGroup()
                        .addComponent(barcode2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barcodeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDetailLayout.createSequentialGroup()
                        .addComponent(barcode1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barcode, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addGap(63, 63, 63))
                    .addGroup(panelDetailLayout.createSequentialGroup()
                        .addComponent(barcode3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetailLayout.createSequentialGroup()
                        .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barcode5)
                            .addComponent(barcode4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(total)
                            .addComponent(diskon, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDetailLayout.setVerticalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barcode2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBarcodeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barcodeName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBarcodeName1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(barcode4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcode5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBarcodeName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(barcode3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelBarcodeName2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void progressText7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressText7MouseClicked

        JTextField field = (JTextField) instance.jComboBox1.getEditor().getEditorComponent();
        field.setText("");
        instance.setToTable();
        instance.jComboBox1.requestFocus();
        dispose();
        Kasir.isDetailShow = false;

    }//GEN-LAST:event_progressText7MouseClicked

    private void totalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyReleased
        TotalEvent();
    }//GEN-LAST:event_totalKeyReleased

    private void totalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyPressed
        sendDetail(evt);
    }//GEN-LAST:event_totalKeyPressed

    private void diskonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diskonKeyReleased
        // TODO add your handling code here:
        TotalEvent();
    }//GEN-LAST:event_diskonKeyReleased

    private void diskonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diskonKeyPressed
        // TODO add your handling code here:
        sendDetail(evt);
    }//GEN-LAST:event_diskonKeyPressed

    void TotalEvent() {
        NumberValidation validation = new NumberValidation(",", null);
        total.setText(validation.fieldChecked(total.getText()));
        NumberValidation valid = new NumberValidation(",", "Rp ");
        if(diskon.getText().equals("Rp ")){
            diskon.setText("Rp ");
            setCostTotal(total.getText().replace(",", ""), "0");
        }
        else{
            diskon.setText(valid.fieldChecked(diskon.getText()));
            setCostTotal(total.getText().replace(",", ""), diskon.getText().replace("Rp ", "").replace(",", ""));
        }
    }

    /**
     * Menghitung biaya untuk pembelian tiap barang
     *
     * @param jumlah
     */
    void setCostTotal(String jumlah, String diskon) {
        try {
            BigInteger spinnerValue = BigInteger.valueOf(Long.parseLong(jumlah));
            BigInteger diskonValue = BigInteger.valueOf(Long.parseLong(diskon));
            long price = (!dataSelected.get(7).isEmpty()) ? (Long.parseLong(dataSelected.get(3)) / Long.parseLong(dataSelected.get(7)))
                    : Long.parseLong(dataSelected.get(3));
            BigInteger costTotal = (spinnerValue.multiply(BigInteger.valueOf(price))).subtract(diskonValue);
            NumberValidation nv = new NumberValidation(",", "Rp ");
            cost.setText(nv.fieldChecked(String.valueOf(costTotal)));
        } catch (Exception e) {
            NumberValidation nv = new NumberValidation(",", "Rp ");
            cost.setText(nv.fieldChecked(textIdentifier[2]));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barcode;
    private javax.swing.JLabel barcode1;
    private javax.swing.JLabel barcode2;
    private javax.swing.JLabel barcode3;
    private javax.swing.JLabel barcode4;
    private javax.swing.JLabel barcode5;
    private javax.swing.JLabel barcodeName;
    private javax.swing.JLabel cost;
    private javax.swing.JTextField diskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelBarcode;
    private javax.swing.JLabel labelBarcodeName;
    private javax.swing.JLabel labelBarcodeName1;
    private javax.swing.JLabel labelBarcodeName2;
    private javax.swing.JLabel labelBarcodeName4;
    private javax.swing.JPanel panelDetail;
    private javax.swing.JLabel progressText1;
    private javax.swing.JLabel progressText7;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
