/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bundaran.kasir.view;

import annas.jdbc.service.configuration.DatabaseTableList;
import annas.jdbc.service.configuration.MyTableModel;
import annas.jdbc.service.impl.SqlImplementImpl;
import annas.jdbc.service.model.QueryAttribut;
import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import bundaran.kasir.TokoBangunanKasir;
import bundaran.kasir.util.MoveFrameListener;
import bundaran.kasir.util.OnlineTransactionSaver;
import bundaran.kasir.view.progress.RequestProgress;

/**
 *
 * @author HAMSTER-BIRU
 */
public final class TransaksiTunda extends javax.swing.JDialog {

    ArrayList<ArrayList<String>> dataPembeli;
    ArrayList<ArrayList<String>> dataBarang;
    Kasir kasir;

    /**
     * Creates new form aboutVersion
     *
     * @param kasir
     */
    public TransaksiTunda(Kasir kasir) {
        super((Frame) null, true);

        this.kasir = kasir;
        initComponents();
        setLocationRelativeTo(null);

        try {
            getDatas();
        } catch (RemoteException ex) {
            Logger.getLogger(TransaksiTunda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void getDatas() throws RemoteException {

        QueryAttribut qAttribut;
        SqlImplementImpl query = new SqlImplementImpl();
        dataPembeli = new ArrayList<>();
        dataBarang = new ArrayList<>();

        qAttribut = new QueryAttribut(false, null, DatabaseTableList.getTableNames()[5], "");
        dataBarang = query.goSelect(qAttribut);

//        QueryAttribut qAttribut1;
        //SqlImplementImpl query1 = new SqlImplementImpl();
        query = new SqlImplementImpl();
        qAttribut = new QueryAttribut(false, null, DatabaseTableList.getTableNames()[3], "");
        dataPembeli = query.goSelect(qAttribut);

        String[] colNames = new String[]{"ID transaksi", "Tanggal Transaksi", "Pembeli", "Kontak",
            "Status", "Jatuh Tempo", "Pembayaran", "Diskon", "Nilai Transaksi(Rp)", "Alamat", "Terbayar", "Kasir"};

        MyTableModel model = new MyTableModel(colNames, dataPembeli, false, true, new int[]{3}, ",");
        tableDataPembeli.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        progressText1 = new javax.swing.JLabel();
        progressText7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDataPembeli = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N

        MoveFrameListener frameListenerx = new MoveFrameListener(jPanel2);
        addMouseListener(frameListenerx);
        addMouseMotionListener(frameListenerx);
        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        progressText1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        progressText1.setForeground(new java.awt.Color(255, 255, 255));
        progressText1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/kasir/res/logo14.PNG"))); // NOI18N
        progressText1.setText("   Transaksi Tunda");

        progressText7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        progressText7.setForeground(new java.awt.Color(255, 255, 255));
        progressText7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/kasir/res/close.png"))); // NOI18N
        progressText7.setToolTipText("Tutup");
        progressText7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progressText7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(progressText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 882, Short.MAX_VALUE)
                .addComponent(progressText7)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(progressText7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(progressText1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addContainerGap())
        );

        tableDataPembeli.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        tableDataPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDataPembeli.setRowHeight(30);
        tableDataPembeli.getTableHeader().setReorderingAllowed(false);
        tableDataPembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataPembeliMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableDataPembeliMousePressed(evt);
            }
        });
        tableDataPembeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableDataPembeliKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableDataPembeli);
        tableDataPembeli.setDefaultRenderer(Object.class, new TableCellRenderer() {
            private DefaultTableCellRenderer DEFAULT_RENDERER = new DefaultTableCellRenderer();

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = DEFAULT_RENDERER.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (isSelected) {
                    c.setBackground(new Color(0xff8a00));
                } else {
                    c.setBackground(new Color(0xffffff));
                }

                return c;
            }

        });

        jLabel13.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel13.setText("Toko Bundaran Elektronik, Kendari, Sulawesi Tenggara");

        jButton1.setUI(new bundaran.kasir.util.WarningUI());
        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/kasir/res/sinkron.PNG"))); // NOI18N
        jButton1.setText("Sinkronkan   ");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("DATA-DATA TRANSAKSI YANG BELUM TERSINKRON DENGAN DATABASE PUSAT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel13)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableDataPembeliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataPembeliMousePressed


    }//GEN-LAST:event_tableDataPembeliMousePressed

    private void tableDataPembeliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableDataPembeliKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                int row = tableDataPembeli.getSelectedRow();

                findTransaction(dataPembeli.get(row).get(0)); // 0 untuk urutan ID transaksi
            } catch (Exception e) {
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        }


    }//GEN-LAST:event_tableDataPembeliKeyPressed

    private void progressText7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressText7MouseClicked

        dispose();
    }//GEN-LAST:event_progressText7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (dataPembeli.isEmpty()) {
            return;
        }
        
        if (!TokoBangunanKasir.OFFLINE_MODE) {

            dispose();

            String backTaskID = TokoBangunanKasir.getIDTask();

            RequestProgress rp = new RequestProgress(this.kasir, backTaskID);
            rp.setVisible(true);
            OnlineTransactionSaver ots = new OnlineTransactionSaver(kasir, backTaskID, rp);
            ots.executeAll(dataPembeli, dataBarang);
        } else {
            JOptionPane.showMessageDialog(null, "Mohon Gunakan Online Mode...");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private ArrayList<ArrayList<String>> dataBarangBy(String id) {
        ArrayList<ArrayList<String>> list = new ArrayList<>();

        for (ArrayList<String> arrayList : dataBarang) {
            if (arrayList.get(1).equals(id)) {
                list.add(arrayList);
            }
        }

        return list;
    }


    private void tableDataPembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataPembeliMouseClicked

        try {
            int row = tableDataPembeli.getSelectedRow();
            if (evt.getClickCount() == 2) {
                findTransaction(dataPembeli.get(row).get(0)); // 0 untuk urutan ID transaksi
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_tableDataPembeliMouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private ArrayList<ArrayList<String>> getDatabarang(String id) {

        ArrayList<ArrayList<String>> r = new ArrayList<>();

        for (ArrayList<String> t : dataBarang) {
            ArrayList<String> temp = new ArrayList<>();
            if (t.get(1).toLowerCase().equals(id.toLowerCase())) {
                temp.add(t.get(0));
                int harga = 0;
                for (ArrayList<String> t2 : kasir.dataBarang) {
                    if (t.get(0).equals(t2.get(0))) {
                        harga = Integer.parseInt(t2.get(3));
                        temp.add(t2.get(1));
                        break;
                    }
                }
                temp.add(t.get(3));
                temp.add(t.get(4));

                int total = Integer.parseInt(t.get(4)) * harga;
                temp.add(String.valueOf(total));

                r.add(temp);
            }
        }

        return r;
    }

    private void findTransaction(String id) {
        if (dataPembeli == null) {
            return;
        }

        for (ArrayList<String> dt : dataPembeli) {
            if (dt.get(0).toLowerCase().equals(id.toLowerCase())) {
                //dispose();
                ArrayList<ArrayList<String>> d = getDatabarang(id);
                new TransaksiTundaDetail(kasir, dt, d).setVisible(true);
                //new HasilCari(kasir, dt, d, dBarangOri).setVisible(true);
                return;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel progressText1;
    private javax.swing.JLabel progressText7;
    private javax.swing.JTable tableDataPembeli;
    // End of variables declaration//GEN-END:variables
}
