/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bundaran.administrator.view;

import annas.jdbc.service.impl.SqlImplementImpl;
import annas.jdbc.service.model.PreparingSQLWriting;
import com.onbarcode.barcode.Code39;
import java.awt.Frame;
import java.awt.Image;
import java.io.File;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingWorker;
import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;
import sun.awt.AppContext;
import bundaran.administrator.TokoBangunanAdministrator;
import bundaran.administrator.backgroundtask.LocalRequestVoidCallbackTask;
import bundaran.administrator.internet.entity.ProductEnt;
import bundaran.administrator.internet.entity.ProductOutEnt;
import bundaran.administrator.internet.impl.ProductImpl;
import bundaran.administrator.internet.impl.ProductOutedImpl;
import bundaran.administrator.util.ComboKeyController;
import bundaran.administrator.util.ComponentIdentifier;
import bundaran.administrator.util.ComponentProcess;
import bundaran.administrator.util.CustomComboBox;
import bundaran.administrator.util.MoveFrameListener;
import bundaran.administrator.util.NumberValidation;
import bundaran.administrator.util.staticIdentifier;
import bundaran.administrator.view.progress.RequestProgress;

/**
 *
 * @author AsyncTask.Void.087
 */
public final class DataBarangKeluarSubMain extends javax.swing.JDialog implements LocalRequestVoidCallbackTask {

    public String[] array = {};
    /**
     * Creates new form DataBarangSubMain
     */
    Object instance;
    ArrayList<ArrayList<String>> dataBarang;
    ComponentProcess componentProcess;

    public DataBarangKeluarSubMain(Object instance, ArrayList<ArrayList<String>> dataSelected) {
        super((Frame) null, true);
        this.instance = instance;
        this.dataBarang = dataSelected;
        array = makeStringSuggestionProduct();

        initComponents();
        setLocationRelativeTo(null);

        jComboBox1.requestFocus();
    }

    public static JComboBox<String> makeComboBox(String... model) {
        return new JComboBox<>(model);
    }

    public String[] makeStringSuggestionProduct() {
        String[] data = new String[dataBarang.size()];

        int i = 0;
        for (ArrayList<String> list : dataBarang) {
            String temp = list.get(0) + "                     Dengan nama barang : " + list.get(1);
            data[i] = temp;
            i++;
        }

        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inventorySite = new javax.swing.JComboBox<>();
        extraType = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        actionButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        productDateIn = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Tujuan = new javax.swing.JLabel();
        tujuanSite = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        progressText2 = new javax.swing.JLabel();
        progressText3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        progressText1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel4.setBackground(new java.awt.Color(246, 246, 246));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Nama Barang");

        productName.setEditable(false);
        productName.setBackground(new java.awt.Color(255, 255, 255));
        productName.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        productName.setForeground(new java.awt.Color(0, 153, 51));
        productName.setMargin(new java.awt.Insets(2, 10, 2, 10));
        productName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productNameKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("Gudang Asal");

        inventorySite.setRenderer(new CustomComboBox());
        inventorySite.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        inventorySite.setForeground(new java.awt.Color(0, 153, 51));
        inventorySite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "Gudang" }));

        extraType.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        extraType.setText("Jumlah");

        jumlah.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jumlah.setForeground(new java.awt.Color(0, 153, 51));
        jumlah.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jumlahKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahKeyReleased(evt);
            }
        });

        actionButton.setUI(new bundaran.administrator.util.WarningUI());
        actionButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        actionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/administrator/res/save.PNG"))); // NOI18N
        actionButton.setText("Simpan Data   ");
        actionButton.setFocusable(false);
        actionButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        actionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                actionButtonMouseEntered(evt);
            }
        });
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel13.setText("Toko Bundaran Elektronik, Kendari, Sulawesi Tenggara");

        productDateIn.setDateFormatString("yyyy-MM-dd");
        productDateIn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setText("Tanggal Barang Keluar Masuk");

        jComboBox1 = makeComboBox(array);
        jComboBox1.setEditable(true);
        //(()jComboBox1.getEditor().getEditorComponent())
        //JTextField jtf = (JTextField) jComboBox1.getEditor().getEditorComponent();
        //jtf.setBorder(BorderFactory.createMatteBorder(0,0,1,0,Color.black));
        //jtf.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jComboBox1.setSelectedItem("");
        jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBox1.setRenderer(new CustomComboBox());
        jComboBox1.setSelectedIndex(-1);
        JTextField field = (JTextField) jComboBox1.getEditor().getEditorComponent();
        field.setText("");
        field.addKeyListener(new ComboKeyController(this, jComboBox1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel11.setText("Pilih Barang");

        Tujuan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Tujuan.setText("Tujuan Keluar Barang");

        tujuanSite.setRenderer(new CustomComboBox());
        tujuanSite.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tujuanSite.setForeground(new java.awt.Color(0, 153, 51));
        tujuanSite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "Toko Bundaran Elektronik" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(actionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel2)
                                                            .addComponent(jLabel7)
                                                            .addComponent(extraType, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(94, 94, 94))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(productDateIn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(inventorySite, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tujuanSite, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inventorySite, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(extraType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productDateIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tujuanSite, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(actionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        MoveFrameListener frameListener = new MoveFrameListener(jPanel3);
        addMouseListener(frameListener);
        addMouseMotionListener(frameListener);
        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        progressText2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        progressText2.setForeground(new java.awt.Color(255, 255, 255));
        progressText2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/administrator/res/close.png"))); // NOI18N
        progressText2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progressText2MouseClicked(evt);
            }
        });

        progressText3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        progressText3.setForeground(new java.awt.Color(255, 255, 255));
        progressText3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokobangunan/administrator/res/logo14.PNG"))); // NOI18N
        progressText3.setText("   Aplikasi Pendataan Barang Toko Bundaran Elektronik");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(progressText3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressText2)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progressText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressText3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel1.setText("Pastikan Data Barang sudah Benar!!! ");

        progressText1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        progressText1.setText("Data Barang yang akan dikeluarkan");

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(progressText1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addContainerGap(38, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressText1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void requestToServer(ArrayList<Object> object, String process) {
        String backTaskID = TokoBangunanAdministrator.getIDTask();
        RequestProgress progress = new RequestProgress(this, backTaskID);
        progress.setVisible(true);

        //List<NameValuePair> list = new ArrayList<>();
        ProductEnt ent = new ProductEnt(progress, object, process, "Mohon menunggu...");
        ProductImpl impl = new ProductImpl(backTaskID, instance);

        if (process.equals("SAVE_PRODUCT")) {
            impl.enchanceSave(ent);
        } else {
            impl.enchanceUpdate(ent);
        }

    }

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed

        if (jumlah.getText().isEmpty() || tujuanSite.getSelectedIndex() == 0) {
            return;
        }


        String tujuan = String.valueOf(tujuanSite.getSelectedItem());
        String jumlahBarang = String.valueOf(this.jumlah.getText());
        Date date = productDateIn.getDate();
        String value = new SimpleDateFormat("yyyy-MM-dd").format(date);

        List<NameValuePair> pairing = new ArrayList<>();
        pairing.add(new BasicNameValuePair("id_keluar", id()));
        pairing.add(new BasicNameValuePair("nomor_barcode", dataSelected.get(0)));
        pairing.add(new BasicNameValuePair("tanggal_keluar", value));
        pairing.add(new BasicNameValuePair("jumlah", jumlahBarang));
        pairing.add(new BasicNameValuePair("tujuan", tujuan));

        String backTaskID = TokoBangunanAdministrator.getIDTask();
        RequestProgress progress = new RequestProgress(this, backTaskID);
        progress.setVisible(true);

        ProductOutEnt outEnt = new ProductOutEnt(progress, pairing, "SAVE_PRODUCT_OUT", "Mohon mennggu...");
        ProductOutedImpl impl = new ProductOutedImpl(backTaskID, instance);
        impl.enchanceSave(outEnt);


    }//GEN-LAST:event_actionButtonActionPerformed

    private String id() {
        Date date = new Date();
        String id = String.valueOf(new SimpleDateFormat("yyyyddHHmmss").format(date));
        return "OUT" + id;
    }


    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        productName.requestFocus();

    }//GEN-LAST:event_formWindowGainedFocus


    private void jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyReleased

        NumberValidation validation = new NumberValidation(".", null);
        jumlah.setText(validation.fieldChecked(jumlah.getText()));

    }//GEN-LAST:event_jumlahKeyReleased

    private void actionButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionButtonMouseEntered

    }//GEN-LAST:event_actionButtonMouseEntered

    private void productNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productNameKeyPressed
        try {
            ComponentIdentifier.menu.setVisible(false);
            ((JTextField) evt.getComponent()).requestFocus();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_productNameKeyPressed

    private void jumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyPressed
        try {
            ComponentIdentifier.menu.setVisible(false);
            ((JTextField) evt.getComponent()).requestFocus();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jumlahKeyPressed

    private void progressText2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressText2MouseClicked

        dispose();

    }//GEN-LAST:event_progressText2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new DataBarangKeluarSubMain(args, null).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tujuan;
    private javax.swing.JButton actionButton;
    private javax.swing.JLabel extraType;
    private javax.swing.JComboBox<String> inventorySite;
    private com.toedter.calendar.JCalendar jCalendar1;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jumlah;
    private com.toedter.calendar.JDateChooser productDateIn;
    private javax.swing.JTextField productName;
    private javax.swing.JLabel progressText1;
    private javax.swing.JLabel progressText2;
    private javax.swing.JLabel progressText3;
    private javax.swing.JComboBox<String> tujuanSite;
    // End of variables declaration//GEN-END:variables

    ArrayList<String> dataSelected;

    private ArrayList<String> getSelectedProduct(String barcode) {
        ArrayList<String> temp = new ArrayList<>();

        for (ArrayList<String> string : dataBarang) {
            if (string.get(0).equals(barcode)) {
                idBacode = barcode;
                temp = string;
                return temp;
            }
        }

        return temp;
    }

    String idBacode = "";

    @Override
    public void processDone(String resultMessage) throws SQLException {

        if (resultMessage.length() >= 12) {

            dataSelected = getSelectedProduct(resultMessage.substring(0, 12));
            if (!dataSelected.isEmpty()) {
                productName.setText(dataSelected.get(1));
                inventorySite.setSelectedItem(dataSelected.get(8));
            }
        }

    }

}
